maslined/urls.py
from django.conf.urls import patterns, include, url, static
from django.contrib import admin
from django.conf import settings

urlpatterns = patterns('',
	url(r'^', include('store.urls', namespace='store')),
    url(r'^admin/', include(admin.site.urls)),
) + static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('store.views',
	url(r'^$', 'index', name='index'),
	url(r'^(services|about|news)$', 'other', name='other'),
	url(r'^linecard$', 'linecard', name='linecard'),
	url(r'^contact$', 'contact', name='contact'),
	url(r'^catalog$', 'catalog', name='catalog'),
	url(r'p/([^/]*)$', 'product', name='product')
)

store/models.py
from django.db import models
from django.db.models.signals import post_delete, pre_save
from django.dispatch import receiver
from django.utils.text import slugify


class Image(models.Model):
	description = models.CharField(max_length=50, verbose_name="Description of Image", blank=True)
	picture = models.ImageField(upload_to='imgs/full', db_index=True)

	def thumbnail(self):
		return '<img src="{0}" height="125px" />'.format(self.picture.url)
	thumbnail.allow_tags = True

	def __str__(self):
		return self.picture.name


@receiver(pre_save, sender=Image)
def article_remove_old_pics_on_save(sender, **kwargs):
	instance = kwargs['instance']
	if instance.id is not None:
		prev_image = sender.objects.get(id=instance.id).picture
		storage, path = prev_image.storage, prev_image.path
		storage.delete(path)


@receiver(post_delete, sender=Image)
def article_remove_old_pics_on_delete(sender, **kwargs):
	instance = kwargs['instance']
	prev_image = instance.picture
	storage, path = prev_image.storage, prev_image.path
	storage.delete(path)


class Logo(models.Model):
	description = models.CharField(max_length=50, verbose_name="Description of Logo", blank=True)
	picture = models.ImageField(upload_to='imgs/logo')

	def thumbnail(self):
		return '<img src="{0}" height="125px" />'.format(self.picture.url)
	thumbnail.allow_tags = True

	def __str__(self):
		return self.picture.name


@receiver(pre_save, sender=Logo)
def article_remove_old_pics_on_save(sender, **kwargs):
	instance = kwargs['instance']
	if instance.id is not None:
		prev_image = sender.objects.get(id=instance.id).picture
		storage, path = prev_image.storage, prev_image.path
		storage.delete(path)


@receiver(post_delete, sender=Logo)
def article_remove_old_pics_on_delete(sender, **kwargs):
	instance = kwargs['instance']
	prev_image = instance.picture
	storage, path = prev_image.storage, prev_image.path
	storage.delete(path)


class Manufacturer(models.Model):
	name = models.CharField(max_length=50, db_index=True)
	home_page = models.URLField(blank=True)
	logo = models.ForeignKey(Logo, blank=True)
	is_linecard = models.BooleanField(default=False)
	bio = models.TextField(blank=True)

	def logo_thumb(self):
		return '<img src="{0}" height="125px" />'.format(self.logo.picture.url)
	logo_thumb.allow_tags = True

	def __str__(self):
		return self.name


class Attribute(models.Model):
	name = models.CharField(max_length=50, db_index=True)
	position = models.PositiveSmallIntegerField(default=1)
	parent = models.ForeignKey('self', blank=True)

	def __str__(self):
		return self.name


class Price(models.Model):
	price = models.DecimalField(max_digits=15, decimal_places=7)
	min_qty = models.PositiveIntegerField()
	max_qty = models.PositiveIntegerField()

	def __str__(self):
		return '{min} - {max} @ ${price}'.format(min=self.min_qty, max=self.max_qty, price=self.price)


class Product(models.Model):
	item_no = models.CharField(max_length=50, verbose_name="The manufacturer supplied part number", db_index=True)
	manu_no = models.ForeignKey(Manufacturer)
	images = models.ManyToManyField(Image, blank=True)
	attributes = models.ManyToManyField(Attribute, blank=True)
	pricing = models.ManyToManyField(Price, blank=True)
	weight = models.DecimalField(max_digits=15, decimal_places=7, default=0)
	slug_url = models.SlugField(db_index=True)

	def thumbs(self):
		img_list = '<ul>'
		for img in self.images.all():
			img_list += '<li style="list-style-type: none;"><img src="{0}" height="50px" /></li>'.format(img.picture.url)
		img_list += '</ul>'
		if len(self.images.all()) == 0:
			return 'No pictures'
		else:
			return img_list
	thumbs.allow_tags = True

	def prices(self):
		price_tbl = '<table><thead><tr><th>Price</th><th>Min</th><th>Max</th></tr></thead><tbody>'
		for price_obj in self.pricing.all().order_by('min_qty'):
			price_tbl += '<tr><td>{price}</td><td>{min}</td><td>{max}</td></tr>'.format(
				price=price_obj.price, min=price_obj.min_qty, max=price_obj.max_qty)
		price_tbl += '</tbody></table>'
		if len(self.pricing.all()) == 0:
			return 'No prices'
		else:
			return price_tbl
	prices.allow_tags = True

	def __str__(self):
		return self.item_no

store/forms.py
from django import forms
from django.core.validators import RegexValidator


class ContactForm(forms.Form):
	name = forms.CharField(max_length=100)
	company = forms.CharField(max_length=100)
	email = forms.EmailField()
	phone = forms.CharField(required=False,
							   max_length=14,
							   validators=[RegexValidator(regex='^\(?\d{3}\)?(-| |.)?\d{3}(-| |.)?\d{4}$', message='(###) ###-####', code='Invalid number')])
	msg = forms.CharField(widget=forms.Textarea, label="Reason for contacting, include part numbers if applicable")

store/views.py
from django.shortcuts import render, Http404, HttpResponseRedirect
from django.core.mail import send_mail
from store.models import Manufacturer, Product
from store.forms import ContactForm


def index(request):
	return render(request, 'store/index.html')


def catalog(request):
	page_no = request.GET.get('p', '1')
	if page_no == 'all':
		next_page = None
		prev_page = None
		products = Product.objects.order_by('item_no')
	elif page_no.isdigit():
		page_no = int(page_no)
		num_products = Product.objects.count()
		if page_no > num_products:
			page_no -= 1
		elif page_no <= 0:
			page_no = 1
		prev_page = None if page_no == 1 else page_no - 1
		next_page = None if page_no >= num_products else page_no + 1
		products = Product.objects.order_by('item_no')[page_no - 1:page_no]
	else:
		return HttpResponseRedirect('/catalog')

	return render(request, 'store/catalog.html', {'products': products, 'next_page': next_page, 'prev_page': prev_page})


def product(request, item_slug):
	curr_product = Product.objects.get(slug_url=item_slug)
	return render(request, 'store/product.html', {'part': curr_product})


def linecard(request):
	linecards = Manufacturer.objects.filter(is_linecard=True)
	return render(request, 'store/linecard.html', {'manufacts': linecards})


def contact(request):
	if request.method == 'POST':
		submitted_form = ContactForm(request.POST)
		if submitted_form.is_valid():
			name = submitted_form.cleaned_data['name']
			company = submitted_form.cleaned_data['company']
			email = submitted_form.cleaned_data['email']
			phone = submitted_form.cleaned_data['phone']
			msg = submitted_form.cleaned_data['msg']

			email_msg = '{name} has contacted us from {company}.\nYou can reach him back at {email} and {phone}.\nHere is his message:\n\t{msg}'.format(
				name=name, company=company, email=email, phone=phone, msg=msg)

			send_mail('New message from a masline.com visitor!', email_msg, 'website@masline.com', ['wgordon@masline.com'])

			return HttpResponseRedirect('/')
		else:
			return render(request, 'store/contact_us.html', {'form': submitted_form})
	else:
		new_form = ContactForm()
		return render(request, 'store/contact_us.html', {'form': new_form})


def other(request, page_name):
	page_data = {
		'catalog': 'Masline\'s extensive catalog',
		'services': 'Masline\'s world renowned services',
		'about': 'us!',
		'news': 'some boring news',
	}.get(page_name, None)
	if page_data is None:
		raise Http404
	return render(request, 'store/other_pages.html', {'page_title': page_name.title(), 'page_data': page_data})

store/templates/store/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head lang="en">
	<meta charset="UTF-8">
	<title>{% block title %}{% endblock %}</title>
</head>
<body>
	<header>
		<div id="top-logo" class="clear">
			<a href="/"><img src="{% static 'store/logo.png' %}" /></a>
		</div>
		<nav>
			<ul class="clear">
				<li><a href="/">Home</a></li>
				<li><a href="/catalog">Catalog</a></li>
				<li><a href="/services">Services</a></li>
				<li><a href="/about">About Us</a></li>
				<li><a href="/news">News</a></li>
				<li><a href="/linecard">Linecard</a></li>
				<li><a href="/contact">Contact Us</a></li>
			</ul>
		</nav>
		<div class="banner"></div>
	</header>

    <div class="content">{% block content %}{% endblock %}</div>

	<style>
		body {
			margin: 0;
			overflow: visible;
		}
		header {
			background: url({% static 'store/header_bg.gif' %}) repeat-x;
			/*text-align: center;*/
			height: 200px;
			width: 100%;
		}
		header .banner {
			background: transparent url({% static 'store/main-sprite.png' %}) repeat-x scroll center -90px;
			height: 333px;
			overflow: hidden;
			width: 100%;
			position: relative;
			z-index: -5;
			top: -282px;
		}
		#top-logo {
			height: 130px;
			padding-top: 15px;
			width: 960px;
			margin: 0 auto;
		}
		nav {
			width: 960px;
			background: transparent url({% static 'store/main-sprite.png' %}) repeat-x scroll left top;
			height: 45px;
			line-height: 45px;
			margin: 0 auto;
			position: relative;
			top: -32px;
		}
		nav ul {
			float: left;
			margin: 0;
		}
		nav ul > li {
			float: left;
			background: transparent url({% static 'store/main-sprite.png' %}) repeat-x scroll left top;
		}
		nav ul > li:hover {
			background-position: left -145px;
		}
		nav a {
			color: #FFF;
			display: block;
			font-size: 25px;
			padding: 0 22px;
			text-decoration: none;
			vertical-align: middle;
		}
		.clear:after {
			content: ".";
			display: block;
			height: 0;
			clear: both;
			visibility: hidden;
		}
		.content {
			width: 900px;
			margin: 20px auto;
		}
		ul > li {
			list-style-type: none;
		}
	</style>
</body>
</html>

store/templates/store/catalog.html
{% extends "store/base.html" %}
{% load staticfiles %}
{% block title %}Catalog | Masline Electronics{% endblock %}

{% block content %}
	<p>
	{% if not prev_page and not next_page %}
		<a href="/catalog?p=1">View paginated</a>
	{% else %}
		<a href="/catalog?p=all">View all</a>
	{% endif %}
	</p>
	<table>
		<thead><tr>
			<th>Part Number</th>
			<th>Manufacturer</th>
			<th>Image</th>
			<th>Pricing</th>
			<th>Weight</th>
		</tr></thead>
		<tbody>
		{% for part in products %}
			<tr>
				{% autoescape off %}
				<td><a href="/p/{{ part.slug_url }}">{{ part.item_no }}</a></td>
				<td>{{ part.manu_no }}</td>
				<td>{{ part.thumbs }}</td>
				<td>{{ part.prices }}</td>
				<td>{{ part.weight }}</td>
				{% endautoescape %}
			</tr>
		{% endfor %}
		</tbody>
	</table>
	{% if prev_page %}
		<a href="/catalog?p={{ prev_page }}" style="float: left;">Previous</a>
	{% endif %}
	{% if next_page %}
		<a href="/catalog?p={{ next_page }}" style="float: right;">Next</a>
	{% endif %}
{% endblock content %}

store/templates/store/contact_us.html
{% extends "store/base.html" %}
{% load staticfiles %}
{% block title %}Contact Masline Electronics{% endblock %}

{% block content %}
	<form action="/contact" method="post">
		{% csrf_token %}
		{{ form }}
		<input type="submit" value="Submit" />
	</form>

	<style>
		label {
			float: left;
			clear: both;
			display: block;
			padding-right: 5px ;
			width: 160px;
			text-align: right;
			margin-bottom: 5px;
		}
		input[type="text"], input[type="email"] {
			float: left;
			width: 390px;
		}
		input[type="submit"] {
			margin: 20px 36%;
		}
		label[for="id_msg"] {
			float: none;
			padding: 20px 0 10px;
			width: 50%;
			margin: 10px 90px -5px;
		}
		textarea {
			display: block;
			margin: 0 170px;
			width: 392px;
			box-sizing: border-box;
		}
		ul.errorlist {
			float: right;
			margin: 0;
			text-align: left;
			width: 300px;
			position: relative;
			top: 3px;
			left: -37px;
			color: red;
		}
	</style>
{% endblock %}

store/templates/store/index.html
{% extends "store/base.html" %}
{% load staticfiles %}
{% block title %}Welcome to Masline Electronics{% endblock %}

{% block content %}
	<p>
		Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.
	</p>
	<p>
		Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar. The Big Oxmox advised her not to do so, because there were thousands of bad Commas, wild Question Marks and devious Semikoli, but the Little Blind Text didn’t listen. She packed her seven versalia, put her initial into the belt and made herself on the way.
	</p>
	<p>
		When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown Bookmarksgrove, the headline of Alphabet Village and the subline of her own road, the Line Lane. Pityful a rethoric question ran over her cheek, then she continued her way. On her way she met a copy.
	</p>
	<p>
		The copy warned the Little Blind Text, that where it came from it would have been rewritten a thousand times and everything that was left from its origin would be the word "and" and the Little Blind Text should turn around and return to its own, safe country. But nothing the copy said could convince her and so it didn’t take long until a few insidious Copy Writers ambushed her, made her drunk with Longe and Parole and dragged her into their agency, where they abused her for their projects again and again. And if she hasn’t been rewritten, then they are still using her. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth. Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One
	</p>
{% endblock %}

store/templates/store/linecard.html
{% extends "store/base.html" %}
{% load staticfiles %}
{% block title %}Welcome to Masline Electronics{% endblock %}

{% block content %}
	<ul>
		{% for manu in manufacts %}
			<li><a href="{{ manu.home_page }}">{{ manu.name }}</a>{{ manu.logo_thumb|safe }}</li>
		{% endfor %}
	</ul>
{% endblock %}

store/templates/store/other_pages.html
{% extends "store/base.html" %}
{% load staticfiles %}
{% block title %}{{ page_title }} | Masline Electronics{% endblock %}

{% block content %}
	<h1>Enjoy reading about {{ page_data }}</h1>
{% endblock %}

store/templates/store/product.html
{% extends "store/base.html" %}
{% load staticfiles %}
{% block title %}{{ part.item_no }} | Masline Electronics{% endblock %}

{% block content %}
	<ul>
		{% autoescape off %}
		<li>{{ part.item_no }}</li>
		<li>{{ part.manu_no }}</li>
		<li>{{ part.thumbs }}</li>
		<li>{{ part.prices }}</li>
		<li>{{ part.weight }}</li>
		{% endautoescape %}
	</ul>
{% endblock content %}